package movies;

public class MoviesArray {
    public static Movie[] findAll() {
        return new Movie[]{
                new Movie("Citizen Kane", "Drama"),
                new Movie("Casablanca", "Drama"),
                new Movie("The Godfather", "Drama"),
                new Movie("Gone With The Wind", "Drama"),
                new Movie("Lawrence Of Arabia", "Drama"),
                new Movie("The Wizard Of Oz", "Musical"),
                new Movie("The Graduate", "Drama"),
                new Movie("On The Waterfront", "Drama"),
                new Movie("Schindler's List", "Drama"),
                new Movie("Singin' In The Rain", "Musical"),
                new Movie("It's A Wonderful Life", "Drama"),
                new Movie("Sunset Boulevard", "Drama"),
                new Movie("The Bridge On The River Kwai", "Drama"),
                new Movie("Some Like It Hot", "Drama"),
                new Movie("Star Wars", "Scifi"),
                new Movie("All About Eve", "Drama"),
                new Movie("The African Queen", "Drama"),
                new Movie("Psycho" , "Horror"),
                new Movie("Chinatown", "Drama"),
                new Movie("One Flew Over The Cuckoo's Nest", "Drama"),
                new Movie("The Grapes Of Wrath", "Drama"),
                new Movie("2001: A Space Odyssey", "Scifi"),
                new Movie("The Maltese Falcon", "Drama"),
                new Movie("Raging Bull", "Drama"),
                new Movie("E.T. The extra-terrestrial", "Scifi"),
                new Movie("Dr. Strangelove", "Drama"),
                new Movie("Bonnie And Clyde", "Drama"),
                new Movie("Apocalypse Now", "Drama"),
                new Movie("Mr. Smith Goes to Washington", "Drama"),
                new Movie("The Treasure Of The Sierra Madre", "Drama"),
                new Movie("Annie Hall", "Comedy"),
                new Movie("The Godfather Part II", "Drama"),
                new Movie("High Noon", "Drama"),
                new Movie("To Kill A Mockingbird", "Drama"),
                new Movie("It Happened One Night", "Drama"),
                new Movie("Midnight Cowboy", "Drama"),
                new Movie("The Best Years Of Our Lives", "Drama"),
                new Movie("Double Indemnity", "Drama"),
                new Movie("Doctor Zhivago", "Drama"),
                new Movie("North By Northwest", "Drama"),
                new Movie("West Side Story", "Musical"),
                new Movie("Rear Window", "Drama"),
                new Movie("King Kong", "Horror"),
                new Movie("The Birth Of A Nation", "Drama"),
                new Movie("A Streetcar Named Desire", "Drama"),
                new Movie("A Clockwork Orange", "Scifi"),
                new Movie("Taxi Driver", "Drama"),
                new Movie("Jaws", "Horror"),
                new Movie("Snow White And The Seven Dwarfs", "Animated"),
                new Movie("Butch Cassidy And The Sundance Kid", "Drama"),
                new Movie("The Philadelphia Story", "Drama"),
                new Movie("From Here To Eternity", "Drama"),
                new Movie("Amadeus", "Drama"),
                new Movie("All Quiet On The Western Front", "Drama"),
                new Movie("The Sound Of Music", "Musical"),
                new Movie("M*A*S*H", "Comedy"),
                new Movie("The Third Man", "Drama"),
                new Movie("Fantasia", "Animated"),
                new Movie("Rebel Without A Cause", "Drama"),
                new Movie("Raiders Of The Lost Ark", "Drama"),
                new Movie("Vertigo", "Drama"),
                new Movie("Tootsie", "Comedy"),
                new Movie("Stagecoach", "Drama"),
                new Movie("Close Encounters Of The Third Kind", "Scifi"),
                new Movie("The Silence Of The Lambs", "Horror"),
                new Movie("Network", "Drama"),
                new Movie("The Manchurian Candidate", "Drama"),
                new Movie("An American In Paris", "Drama"),
                new Movie("Shane", "Drama"),
                new Movie("The French Connection", "Drama"),
                new Movie("Forrest Gump", "Drama"),
                new Movie("Ben-Hur", "Drama"),
                new Movie("Wuthering Heights", "Drama"),
                new Movie("The Gold Rush", "Drama"),
                new Movie("Dances With Wolves", "Drama"),
                new Movie("City Lights", "Drama"),
                new Movie("American Graffiti", "Drama"),
                new Movie("Rocky", "Drama"),
                new Movie("The Deer Hunter", "Drama"),
                new Movie("The Wild Bunch", "Drama"),
                new Movie("Modern Times", "Drama"),
                new Movie("Giant", "Drama"),
                new Movie("Platoon", "Drama"),
                new Movie("Fargo", "Drama"),
                new Movie("Duck Soup", "Comedy"),
                new Movie("Mutiny On The Bounty", "Drama"),
                new Movie("Frankenstein", "Horror"),
                new Movie("Easy Rider", "Drama"),
                new Movie("Patton", "Drama"),
                new Movie("The Jazz Singer", "Drama"),
                new Movie("My Fair Lady", "Musical"),
                new Movie("A Place In The Sun", "Drama"),
                new Movie("The Apartment", "Drama"),
                new Movie("Goodfellas", "Drama"),
                new Movie("Pulp Fiction", "Drama"),
                new Movie("The Searchers", "Drama"),
                new Movie("Bringing Up Baby", "Drama"),
                new Movie("Unforgiven", "Drama"),
                new Movie("Guess Who's Coming To Dinner", "Drama"),
                new Movie("Yankee Doodle Dandy", "Musical")
        };

    }

}